In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

In [12]:
df = pd.read_csv(r"C:\Users\sivap\OneDrive\Desktop\project_2\Salary Data.csv")

In [13]:
df.head()

,Age,Gender,Education Level,Job Title,Years of Experience,Level,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,Medium,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,Fresher,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,Expert,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,Medium,60000.0
4,52.0,Male,Master's,Director,20.0,Expert,200000.0

In [14]:
df.tail()

,Age,Gender,Education Level,Job Title,Years of Experience,Level,Salary
369,35.0,Female,Bachelor's,Senior Marketing Analyst,8.0,Medium,85000.0
370,43.0,Male,Master's,Director of Operations,19.0,Expert,170000.0
371,29.0,Female,Bachelor's,Junior Project Manager,2.0,Fresher,40000.0
372,34.0,Male,Bachelor's,Senior Operations Coordinator,7.0,Medium,90000.0
373,44.0,Female,PhD,Senior Business Analyst,15.0,Expert,150000.0

In [18]:
df.shape

(374, 7)

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  373 non-null    float64
 1   Gender               373 non-null    str
 2   Education Level      373 non-null    str
 3   Job Title            373 non-null    str
 4   Years of Experience  373 non-null    float64
 5   Level                374 non-null    str
 6   Salary               373 non-null    float64
dtypes: float64(3), str(4)
memory usage: 20.6 KB

In [26]:
df.describe()

              Age  Years of Experience         Salary
count  373.000000           373.000000     373.000000
mean    37.431635            10.030831  100577.345845
std      7.069073             6.557007   48240.013482
min     23.000000             0.000000     350.000000
25%     31.000000             4.000000   55000.000000
50%     36.000000             9.000000   95000.000000
75%     44.000000            15.000000  140000.000000
max     53.000000            25.000000  250000.000000

In [23]:
df.columns

Index(['Age', 'Gender', 'Education Level', 'Job Title', 'Years of Experience',
       'Level', 'Salary'],
      dtype='str')